### GET todas as musicas
GET http://localhost:5001/api/songs

### GET uma musica
GET http://localhost:5001/api/songs/2

### GET usuarios
GET http://localhost:5001/api/users

### GET historicos
GET http://localhost:5001/api/histories

### GET historico do user 1
GET http://localhost:5001/api/users

###
POST http://localhost:5001/api/users
Content-Type: application/json

{
  "name": "value2",
  "email": "zegmail.com",
  "password": "ze123"
}

### GET historico do user 1
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
  "email": "aflfonso@gmail.com",
  "password": "123456"
}

###
DELETE http://localhost:5001/api/users/3

###
DELETE http://localhost:5001/api/users
Content-Type: application/json

{
  "email": "alfonso@gmail.com",
  "password": "123456"
}

### GET historico do user 1
GET http://localhost:5001/api/users

###
PUT http://localhost:5001/api/users/1
Content-Type: application/json

{
  "name": "antoim",
  "email": "asdads"
}